### PR TITLE
Added lightweight alpine docker image

### PR DESCRIPTION
**Pull request by khast3x**
Hello,  

This PR adds a `Dockerfile` based on the tiny Alpine linux container.  
Usage is very straightforward, as shown in the `README` instructions.  
This enables an easier integration of `twa` in CI/CD environments to scan web servers automatically, and ensure getting the latest version of your code.  I hope you find it worthwhile.

Best regards,

### CODE REVIEW

**Comment by khast3x** [comment]
Also, in case you might not be aware, you can create a free account on Docker hub and link your Github account. This will enable auto builds of your code with `push` triggers.  If you knew sorry lol
Best regards,

**Comment by khast3x** [comment]
Hello, `nc` is already installed by default (Alpine uses Busybox). The `ncurse` packages contains the `tput` binary. 
Glad to know, thanks :)

**Comment by woodruffw** [comment]
Oh, I had no idea; interesting!

In that case, I'll merge now.

**Comment by woodruffw** [comment]
Thanks @khast3x! I'll set the Docker hub repo up in a moment.

**Comment by woodruffw** [comment]
JFYI, I had to take the docker repo down for a bit (since it got messed up in the GitHub migration). I'll set it up more permanently (with builds pushed from Travis CI) in a bit.

**Comment by woodruffw** [comment]
Should be fixed now.

**Pull request merged**
